name: Deploy
on:
  push:
    branches: [dev]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy to fly.io
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --dockerfile contrib/docker/Dockerfile.apache --local-only
